### ISSUE TITLE
Error while running dag on k8s on-premise

### ISSUE THREAD

**Issue by Santhin** [getindata/dbt-airflow-factory#90]
While trying to run dag on k8s on-premise with `in_cluster` flag:
```yaml
image_pull_policy: IfNotPresent
namespace: change_me
labels:
  runner: airflow

envs:
  POSTGRES_USER: "{{ var.value.get('POSTGRES_USER', 'default') }}"
  POSTGRES_PASSWORD: "{{ var.value.get('POSTGRES_PASSWORD', 'default') }}"

is_delete_operator_pod: True
in_cluster: True
resources:
  limit:
    memory: 512M
    cpu: 1
  requests:
    memory: 512M
    cpu: 1 
```
I'm getting an error 
```bash
Invalid connection configuration. Options kube_config_path, kube_config, in_cluster are mutually exclusive. You can only use one option at a time.
```

The sanity check was to run a simple KPO with a standard config that works fine:
```python
from pendulum import datetime, duration
from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import (
    KubernetesPodOperator,
)

default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "start_date": datetime(2022, 1, 1),
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 1,
    "retry_delay": duration(minutes=5),
}

with DAG(
    dag_id="example_kubernetes_pod", schedule="@once", default_args=default_args
) as dag:
    k = KubernetesPodOperator(
        namespace="change_me",
        image="hello-world",
        name="airflow-test-pod",
        task_id="task-one",
        in_cluster=True,  # if set to true, will look in the cluster, if false, looks for a file
        is_delete_operator_pod=True,
        get_logs=True,
        config_file=None,
    )
```

The problem raises due to [this default value](https://github.com/getindata/dbt-airflow-factory/blob/develop/dbt_airflow_factory/k8s/k8s_parameters.py#L65), which triggers connection config [check](https://github.com/apache/airflow/blob/2.5.1/airflow/providers/cncf/kubernetes/hooks/kubernetes.py#L166)

The easiest solution for this kind of problem it's to change the default value from `"~/.kube/config"` to None like it's done inside [KPO](https://github.com/apache/airflow/blob/2.2.0/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L201)
I've tried to reset the default value by overwriting `config_file`  with `None` inside yaml file but due to serialization this cannot be done because the parser will change this to a string rather than leave the original form
